import sys

file_path = "d:/licenta_practica/AI_Detector_App/app.py"
with open(file_path, 'r', encoding='utf-8') as f:
    content = f.read()

target_anchor = "# ── HEADER PRINCIPAL ──────────────────────────────────────────────────────────"

replacement = """    with st.expander("💡 How to choose the right model?"):
        st.markdown(
            \"\"\"
**RoBERTa v1 (ChatGPT only)**  
Use this model if you specifically suspect the text was generated by **ChatGPT (versions 3.5 or 4)**. Because it was fine-tuned exclusively on OpenAI's specific writing style, it achieves near-perfect accuracy (over 99%) for ChatGPT texts. However, it may struggle to detect text from other AI generators.

**RoBERTa v2 (Multi-model)**  
Use this model as your **default choice** or when the source of the AI text is unknown. It was trained on a highly diverse dataset (including Llama, Claude, Gemini, Mistral, and ChatGPT). It offers significantly better cross-model generalization and robustness across the entire AI landscape.
            \"\"\"
        )

# ── HEADER PRINCIPAL ──────────────────────────────────────────────────────────"""

if target_anchor in content:
    content = content.replace(target_anchor, replacement)
    with open(file_path, 'w', encoding='utf-8') as f:
        f.write(content)
    print("Added the model usage explanation section.")
else:
    print("Could not find the target anchor.")
