import os

replacements = {
    'page_title="TextScan AI - Licenta Farca Flavius"': 'page_title="TextScan AI - Thesis Farca Flavius"',
    '<h1>Detectia textului generat de AI</h1>': '<h1>AI Generated Text Detection</h1>',
    'Modele RoBERTa fine-tuned &nbsp;·&nbsp; Clasificare binara Uman / AI': 'Fine-tuned RoBERTa models &nbsp;·&nbsp; Binary classification Human / AI',
    '&nbsp;·&nbsp; Licenta Farca Flavius': '&nbsp;·&nbsp; Thesis Farca Flavius',
    '<p class="sidebar-section">Sistem</p>': '<p class="sidebar-section">System</p>',
    'MODEL ACTIV': 'ACTIVE MODEL',
    'Antrenat pe texte ChatGPT-3.5 si<br>\nChatGPT-4.': 'Trained on ChatGPT-3.5 and<br>\nChatGPT-4 texts.',
    'Performanta redusa pe alte modele.': 'Reduced performance on other models.',
    'Antrenat pe ChatGPT, Llama, Claude, Gemini, Mistral.<br>\nRobustete superioara pe mai multe modele AI.': 'Trained on ChatGPT, Llama, Claude, Gemini, Mistral.<br>\nSuperior robustness across multiple AI models.',
    '["Scrie / Lipeste text", "Incarca fisier"]': '["Write / Paste text", "Upload file"]',
    'Lipeste sau scrie textul pe care vrei sa il analizezi.': 'Paste or write the text you want to analyze.',
    'Aplicatia analizeaza stilul de scriere si structura lingvistica a textului\npentru a determina daca a fost redactat de un om sau generat de un\nmodel AI. Rezultatele sunt calculate pe baza probabilitatilor returnate de\nmodelul RoBERTa antrenat pe mii de exemple de text uman si text\ngenerat artificial.': 'The application analyzes the writing style and linguistic structure of the text\nto determine whether it was written by a human or generated by an\nAI model. The results are calculated based on the probabilities returned by\nthe RoBERTa model trained on thousands of examples of human and\nartificially generated text.',
    'Pentru rezultate cat mai precise, recomandam un text de cel putin 50\nde cuvinte redactat in limba engleza. Textele foarte scurte pot\ngenera rezultate mai putin fiabile. Daca textul depaseste 128 de tokeni, acesta va fi\ntrunchiat automat la primele 128 de tokeni inainte de analiza.': 'For the most accurate results, we recommend a text of at least 50\nwords written in English. Very short texts may\nproduce less reliable results. If the text exceeds 128 tokens, it will be\nautomatically truncated to the first 128 tokens before analysis.',
    'Exemplu text uman': 'Human text example',
    'Exemplu text AI': 'AI text example',
    'button("Detecteaza"': 'button("Detect"',
    'label="Incarca unul sau mai multe fisiere (.txt, .csv, .pdf)"': 'label="Upload one or more files (.txt, .csv, .pdf)"',
    'Incarca unul sau mai multe fisiere pentru a le analiza.': 'Upload one or more files to analyze them.',
    '<p class="section-label">REZULTAT</p>': '<p class="section-label">RESULT</p>',
    'Niciun text analizat': 'No text analyzed',
    'Scrie sau lipeste text, sau incarca un fisier, apoi apasa Detecteaza': 'Write or paste text, or upload a file, then press Detect',
    'Analiza Batch': 'Batch Analysis',
    'Fisier': 'File',
    'Predictie': 'Prediction',
    'Incarca unul sau mai multe fisiere pentru a incepe detectia.': 'Upload one or more files to start detection.',
    'Generare rapoarte in curs...': 'Generating reports...',
    'Rapoarte descarcate cu succes!': 'Reports successfully downloaded!',
    'label="Descarca raport PDF"': 'label="Download PDF report"',
    'Informatii Text': 'Text Information',
    'Analiza per Fragment': 'Analysis per Fragment',
    'Probabilitate AI': 'AI Probability',
    'Probabilitate Uman': 'Human Probability',
    'TEXTSCAN AI - RAPORT DE ANALIZA': 'TEXTSCAN AI - ANALYSIS REPORT',
    'TEXTSCAN AI - RAPORT:': 'TEXTSCAN AI - REPORT:',
    'Rezultat global:': 'Global result:',
    'Uman': 'Human',
    'Model folosit:': 'Model used:',
    'Fragmente analizate:': 'Analyzed fragments:',
    'TEXT ANALIZAT (fragmentele AI sunt evidentiate cu rosu):': 'ANALYZED TEXT (AI fragments are highlighted in red):',
    'Ponderea AI per fisier:': 'AI ratio per file:',
    'Eroare la procesarea fisierului': 'Error processing file',
    'Timp executie:': 'Execution time:',
    '<span class="token-label">Tokeni</span>': '<span class="token-label">Tokens</span>',
    'fragmente': 'fragments',
    'Total:': 'Total:',
    'Uman / AI': 'Human / AI',
    'TEXTSCAN AI - RAPORT': 'TEXTSCAN AI - REPORT',
    '"Uman"': '"Human"'
}

file_path = "d:/licenta_practica/AI_Detector_App/app.py"

with open(file_path, 'r', encoding='utf-8') as f:
    content = f.read()

for ro, en in replacements.items():
    content = content.replace(ro, en)

# Double check some things that might be slightly differently formatted in python strings
content = content.replace('Antrenat pe texte ChatGPT-3.5 si\\nChatGPT-4.', 'Trained on ChatGPT-3.5 and\\nChatGPT-4 texts.')
content = content.replace('Antrenat pe ChatGPT, Llama, Claude, Gemini, Mistral.<br>\\nRobustete superioara pe mai multe modele AI.', 'Trained on ChatGPT, Llama, Claude, Gemini, Mistral.<br>\\nSuperior robustness across multiple AI models.')

with open(file_path, 'w', encoding='utf-8') as f:
    f.write(content)

print("Translation completed.")
